### ISSUE TITLE
About Test Size of source only testing, SDCA testing and SSL testing

### ISSUE THREAD

**Issue by jiangzhengkai** [BIT-DA/SDCA#3]
Hi, I notice that the size of source-only testing is (1024, 512), SDCA testing is also (1024, 512), while the size of SSL testing is (2048, 1024)? I think the size of ablations should be the same.

**Comment by BinhuiXie** [comment]
Hi, thans for your interest! 
Actually different works utilize slightly different training settings and test settings. And as I mentioned in #2, a larger resolution does help increase our performance.
