### ISSUE TITLE
About code of T-SNE analysis in SDCA

### ISSUE THREAD

**Issue by qianyuzqy** [BIT-DA/SDCA#5]
Dear Author,

Thanks for your fantastic paper, I think it is very interesting. And I notice that you provided the t-SNE analysis for visualization of the embedded features in your paper (Fig. 5), but I did not find it in your code. Could you please upload the implementation on how to perform the t-SNE analysis in your codebase?

I would appreciate it if you could help me. Thank you in advance.

Looking forward to your reply.

Best Regards,
Qianyu

**Comment by BinhuiXie** [comment]
Hi @Qianyu666. It will take some time, because of tedious and heavy jobs these days. 
BTW, I greatly recommend the package of `sklearn.manifold.TSNE`. 
```
TSNE(n_components=2, init='pca', random_state=0)
```

**Comment by BinhuiXie** [comment]
Hello @Qianyu666. Please check [tsne.py](https://github.com/BIT-DA/SDCA/blob/51073908d4eaf39089b58c58c59dc0611ed3b09b/tsne.py).

**Comment by qianyuzqy** [comment]
Hi, Binehui, @BinhuiXie , 
Thank you very much!
Best wishes to you，
